language: clojure
sudo: false
branches:
  only:
  - master
  - staging
sudo: false
services:
- redis-server
script: lein uberjar
before_install:
- openssl aes-256-cbc -K $encrypted_1fe7f0dcdb0a_key -iv $encrypted_1fe7f0dcdb0a_iv -in ./travis/id_rsa.enc -out id_rsa -d
- mv id_rsa .travis/id_rsa
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="reference-prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="reference-stg"; fi
- echo "Deploying to $SERVER"
- cp .travis/known_hosts ~/.ssh/known_hosts
- chmod 600 ~/.ssh/known_hosts
- chmod 600 .travis/id_rsa
- chmod 600 .travis/id_rsa.pub
- ssh-add .travis/id_rsa
- scp -i .travis/id_rsa target/reference-3.0.0-standalone.jar root@104.236.66.244:/apps/$APP/reference-3.0.0-standalone.jar
- scp -i .travis/id_rsa target/reference-3.0.0-standalone.jar root@104.131.17.78:/apps/$APP/reference-3.0.0-standalone.jar
- ssh root@104.236.66.244 "supervisorctl restart $APP"
- ssh root@104.131.17.78 "supervisorctl restart $APP"
notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM
