language: clojure
lein: lein2
branches:
  only:
  - new-master
  - staging
services:
  - redis-server
script: lein2 uberjar
before_install:
- openssl aes-256-cbc -K $encrypted_ca052cba0f72_key -iv $encrypted_ca052cba0f72_iv -in id_rsa.enc -out ./.travis/id_rsa -d
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="reference"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="reference-stg"; fi
- cp .travis/known_hosts ~/.ssh/known_hosts
- chmod 600 ~/.ssh/known_hosts
- chmod 600 .travis/id_rsa
- chmod 600 .travis/id_rsa.pub
- ssh-add .travis/id_rsa
- scp -i .travis/id_rsa target/reference-3.0.0-standalone.jar root@104.236.66.244:/apps/$APP/reference-3.0.0-standalone.jar
- scp -i .travis/id_rsa target/reference-3.0.0-standalone.jar root@104.131.17.78:/apps/$APP/reference-3.0.0-standalone.jar
- ssh root@104.236.66.244 "supervisorctl restart $APP"
- ssh root@104.131.17.78 "supervisorctl restart $APP"
notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM
