language: clojure
lein: lein2
branches:
  only:
  - master
  - staging
services:
  - redis-server
script: lein2 uberjar
before_install:
- openssl aes-256-cbc -K $encrypted_ca052cba0f72_key -iv $encrypted_ca052cba0f72_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="reference-prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="reference-stg"; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then export FRONTEND="45.55.143.82"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export FRONTEND="104.236.66.244"; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then export KEY="id_rsa_prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export KEY="id_rsa"; fi
- cp .travis/known_hosts ~/.ssh/known_hosts
- chmod 600 ~/.ssh/known_hosts
- chmod 600 .travis/id_rsa
- chmod 600 .travis/id_rsa_prod
- scp -i .travis/$KEY target/reference-3.0.0-standalone.jar root@$FRONTEND:/apps/$APP/reference-3.0.0-standalone.jar
- scp -i .travis/id_rsa target/reference-3.0.0-standalone.jar root@104.131.17.78:/apps/$APP/reference-3.0.0-standalone.jar
- ssh root@$FRONTEND "sudo supervisorctl restart $APP"
- ssh root@104.131.17.78 "supervisorctl restart $APP"
notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM
